[paths]
root = "/home/cpjreynolds/cube"
assets = "/home/cpjreynolds/cube/assets"
shaders = "/home/cpjreynolds/cube/shaders"

[window]
multisampling = 2

[projection]
fov = 70.0
znear = 0.1
zfar = 100.0

[camera]
sensitivity = 0.2
radius = 7.5

[player]
diffuse_map = "tiles/container.png"
specular_map = "tiles/container_specular.png"
shine = 32.0
speed = 2.0
scale = 1.0

[light]
scale = 0.2
    [light.position]
    x = 1.0
    y = 1.5
    z = -3.0
    [light.color]
    x = 1.0
    y = 1.0
    z = 1.0
    [light.ambient]
    x = 0.2
    y = 0.2
    z = 0.2
    [light.diffuse]
    x = 0.5
    y = 0.5
    z = 0.5
    [light.specular]
    x = 1.0
    y = 1.0
    z = 1.0

