[paths]
root = "/home/cpjreynolds/cube"
assets = "/home/cpjreynolds/cube/assets"
shaders = "/home/cpjreynolds/cube/shaders"

[window]
multisampling = 2

[projection]
fov = 70.0
znear = 0.1
zfar = 100.0

[camera]
speed = 5.0
sensitivity = 0.05
    [camera.position]
    x = 0.0
    y = 0.0
    z = 5.0
    [camera.target]
    x = 0.0
    y = 0.0
    z = -1.0

[[cube]]
texture = "tiles/brick_red.png"
scale = 0.5
amplitude = 3.14
period = 6.0
pshift = 1.5
    [cube.translation]
    x = 2.0
    y = 1.0
    z = -3.0
    [cube.axis]
    x = 0.0
    y = 1.0
    z = 0.2

[[cube]]
texture = "tiles/water.png"
scale = 0.5
amplitude = 3.14
period = 6.0
pshift = 2.0
    [cube.translation]
    x = -1.5
    y = 0.6
    z = -2.0
    [cube.axis]
    x = 0.7
    y = 1.0
    z = 0.0

[[cube]]
texture = "tiles/redstone_emerald.png"
scale = 0.5
amplitude = 3.14
period = 6.0
pshift = 1.0
    [cube.translation]
    x = 0.1
    y = -1.0
    z = -1.0
    [cube.axis]
    x = 0.2
    y = 0.5
    z = 0.3
